# https://codecov.io/gh/terminal-labs/utilities-package
comment: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
